/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity */
        get: operations["get_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activity_id}/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity Streams */
        get: operations["get_activity_streams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adapt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adapt */
        post: operations["adapt_week"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adjustments/propose/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Adjustment */
        post: operations["propose_adjustment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compliance */
        get: operations["get_compliance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/garmin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Garmin Login */
        post: operations["garmin_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/garmin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Garmin Logout */
        post: operations["garmin_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/garmin/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Garmin Mfa */
        post: operations["garmin_mfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/garmin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Garmin Status */
        get: operations["garmin_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup Goal */
        post: operations["setup_goal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load */
        get: operations["get_load"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan */
        get: operations["get_plan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push */
        post: operations["push_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove */
        post: operations["remove_owned_workouts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_activities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weeks/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Week */
        get: operations["get_week"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Average Hr */
            average_hr?: number | null;
            /**
             * Best Effort
             * @default false
             */
            best_effort?: boolean;
            capture?: components["schemas"]["CaptureStatus"] | null;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Distance Km */
            distance_km: number;
            /** Duration Min */
            duration_min: number;
            /** Hr Zones */
            hr_zones?: components["schemas"]["HeartRateZone"][] | null;
            /** Id */
            id: string;
            kind?: components["schemas"]["Kind"] | null;
            /** Laps */
            laps?: components["schemas"]["RunLap"][] | null;
            metrics?: components["schemas"]["RunMetrics"] | null;
            /** Raw Summary */
            raw_summary?: {
                [key: string]: unknown;
            } | null;
            /**
             * Source
             * @default local
             */
            source?: string;
            /** Splits */
            splits?: components["schemas"]["RunLap"][] | null;
            /**
             * Sport
             * @default running
             */
            sport?: string;
            streams?: components["schemas"]["RunStreams"] | null;
        };
        /** AdaptRequest */
        AdaptRequest: {
            /**
             * Apply
             * @default false
             */
            apply?: boolean;
            /** Week */
            week: number;
        };
        /** Adjustment */
        Adjustment: {
            /** After Minutes */
            after_minutes: number;
            /**
             * Applied
             * @default false
             */
            applied?: boolean;
            /** Before Minutes */
            before_minutes: number;
            /** Factor */
            factor: number;
            /** Reasons */
            reasons: string[];
            /** Week */
            week: number;
        };
        /** Athlete */
        Athlete: {
            /**
             * Max Hr
             * @default 190
             */
            max_hr?: number;
            /**
             * Resting Hr
             * @default 60
             */
            resting_hr?: number;
            /**
             * Trimp A
             * @default 0.64
             */
            trimp_a?: number;
            /**
             * Trimp B
             * @default 1.92
             */
            trimp_b?: number;
        };
        /** BackfillResult */
        BackfillResult: {
            /**
             * Completed
             * @default 0
             */
            completed?: number;
            /**
             * Failed
             * @default 0
             */
            failed?: number;
            /**
             * Remaining
             * @default 0
             */
            remaining?: number;
        };
        /** CaptureStatus */
        CaptureStatus: {
            /** Attempts */
            attempts: number;
            /** Error */
            error?: string | null;
            /** Fetched At */
            fetched_at?: string | null;
            /**
             * Fit Archived
             * @default false
             */
            fit_archived?: boolean;
            /** State */
            state: string;
        };
        /** Created */
        Created: {
            fitness: components["schemas"]["Fitness"];
            /** Plan Id */
            plan_id: string;
            /** Sessions */
            sessions: number;
            /** Warnings */
            warnings: string[];
        };
        /** Error */
        Error: {
            /** Detail */
            detail: string;
        };
        /** Fitness */
        Fitness: {
            /** Easy Pace */
            easy_pace: number | null;
            /** Source */
            source: string;
            /** Vdot */
            vdot: number | null;
            /** Weekly Minutes */
            weekly_minutes: number;
        };
        /** GarminLogin */
        GarminLogin: {
            /** Email */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** GarminLoginResult */
        GarminLoginResult: {
            /** Challenge Id */
            challenge_id?: string | null;
            /** Connected */
            connected: boolean;
            /** Display Name */
            display_name?: string | null;
            /** Expires At */
            expires_at?: number | null;
            /**
             * Mfa Required
             * @default false
             */
            mfa_required?: boolean;
        };
        /** GarminMFA */
        GarminMFA: {
            /** Challenge Id */
            challenge_id: string;
            /**
             * Code
             * Format: password
             */
            code: string;
        };
        /** GarminStatus */
        GarminStatus: {
            /** Connected */
            connected: boolean;
            /** Display Name */
            display_name?: string | null;
            /** Expires At */
            expires_at?: number | null;
        };
        /**
         * Goal
         * @enum {string}
         */
        Goal: "5k" | "10k" | "half" | "marathon" | "return-to-running";
        /** GoalRequest */
        GoalRequest: {
            /** Recent Runs */
            recent_runs?: components["schemas"]["Activity"][] | null;
            setup: components["schemas"]["Setup"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartRateZone */
        HeartRateZone: {
            /** Lower Bpm */
            lower_bpm?: number | null;
            /** Seconds */
            seconds: number;
            /** Upper Bpm */
            upper_bpm?: number | null;
            /** Zone */
            zone: number;
        };
        /**
         * Kind
         * @enum {string}
         */
        Kind: "easy" | "long" | "tempo" | "intervals" | "recovery" | "run-walk";
        /** Load */
        Load: {
            /** Completed Minutes */
            completed_minutes: number;
            /** Missing Hr */
            missing_hr: number;
            /** Trimp */
            trimp: number;
            /** Week */
            week: number;
        };
        /** Match */
        Match: {
            /** Activity Id */
            activity_id: string;
            /** Method */
            method: string;
            /** Workout Id */
            workout_id: string;
        };
        /** Metrics */
        Metrics: {
            /** Completed Minutes */
            completed_minutes: number;
            /** Compliance */
            compliance: number;
            /** Matched Sessions */
            matched_sessions: number;
            /** Matches */
            matches: components["schemas"]["Match"][];
            /** Missing Hr */
            missing_hr: number;
            /** Planned Minutes */
            planned_minutes: number;
            /** Planned Sessions */
            planned_sessions: number;
            /** Trimp */
            trimp: number;
            /** Week */
            week: number;
        };
        /** Plan */
        Plan: {
            fitness: components["schemas"]["Fitness"];
            /** Id */
            id: string;
            setup: components["schemas"]["Setup"];
            /** Warnings */
            warnings?: string[];
            /** Workouts */
            workouts: components["schemas"]["Workout"][];
        };
        /** Proposal */
        Proposal: {
            adjustment: components["schemas"]["Adjustment"];
            /**
             * Preview Only
             * @default true
             */
            preview_only?: boolean;
            /**
             * Requires Closed Week And Sync
             * @default true
             */
            requires_closed_week_and_sync?: boolean;
        };
        /** PushRequest */
        PushRequest: {
            /**
             * Apply
             * @default false
             */
            apply?: boolean;
            /**
             * Dry Run
             * @default false
             */
            dry_run?: boolean;
            /** Week */
            week?: number | null;
            /** Workout */
            workout?: string | null;
        };
        /** RemoveRequest */
        RemoveRequest: {
            /**
             * Apply
             * @default false
             */
            apply?: boolean;
            /**
             * Dry Run
             * @default false
             */
            dry_run?: boolean;
        };
        /** RunDetail */
        RunDetail: {
            /** Average Hr */
            average_hr?: number | null;
            /**
             * Best Effort
             * @default false
             */
            best_effort?: boolean;
            capture?: components["schemas"]["CaptureStatus"] | null;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Distance Km */
            distance_km: number;
            /** Duration Min */
            duration_min: number;
            /** Hr Zones */
            hr_zones?: components["schemas"]["HeartRateZone"][] | null;
            /** Id */
            id: string;
            kind?: components["schemas"]["Kind"] | null;
            /** Laps */
            laps?: components["schemas"]["RunLap"][] | null;
            metrics?: components["schemas"]["RunMetrics"] | null;
            /** Raw Summary */
            raw_summary?: {
                [key: string]: unknown;
            } | null;
            /** Splits */
            splits?: components["schemas"]["RunLap"][] | null;
            /**
             * Sport
             * @default running
             */
            sport?: string;
        };
        /** RunLap */
        RunLap: {
            /** Average Cadence Spm */
            average_cadence_spm?: number | null;
            /** Average Hr */
            average_hr?: number | null;
            /** Average Pace S Km */
            average_pace_s_km?: number | null;
            /** Average Power W */
            average_power_w?: number | null;
            /** Distance M */
            distance_m: number;
            /** Duration S */
            duration_s: number;
            /** Elevation Gain M */
            elevation_gain_m?: number | null;
            /** Elevation Loss M */
            elevation_loss_m?: number | null;
            /** Max Hr */
            max_hr?: number | null;
            /** Max Power W */
            max_power_w?: number | null;
        };
        /** RunMetrics */
        RunMetrics: {
            /** Aerobic Training Effect */
            aerobic_training_effect?: number | null;
            /** Anaerobic Training Effect */
            anaerobic_training_effect?: number | null;
            /** Average Cadence Spm */
            average_cadence_spm?: number | null;
            /** Average Pace S Km */
            average_pace_s_km?: number | null;
            /** Average Power W */
            average_power_w?: number | null;
            /** Average Speed M S */
            average_speed_m_s?: number | null;
            /** Average Temperature C */
            average_temperature_c?: number | null;
            /** Calories */
            calories?: number | null;
            /** Device */
            device?: string | null;
            /** Elapsed Time S */
            elapsed_time_s?: number | null;
            /** Elevation Gain M */
            elevation_gain_m?: number | null;
            /** Elevation Loss M */
            elevation_loss_m?: number | null;
            /** Ground Contact Time Ms */
            ground_contact_time_ms?: number | null;
            /** Max Cadence Spm */
            max_cadence_spm?: number | null;
            /** Max Elevation M */
            max_elevation_m?: number | null;
            /** Max Hr */
            max_hr?: number | null;
            /** Max Pace S Km */
            max_pace_s_km?: number | null;
            /** Max Power W */
            max_power_w?: number | null;
            /** Max Speed M S */
            max_speed_m_s?: number | null;
            /** Max Temperature C */
            max_temperature_c?: number | null;
            /** Min Elevation M */
            min_elevation_m?: number | null;
            /** Min Temperature C */
            min_temperature_c?: number | null;
            /** Moving Time S */
            moving_time_s?: number | null;
            /** Normalized Power W */
            normalized_power_w?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Stride Length Cm */
            stride_length_cm?: number | null;
            /** Timezone */
            timezone?: string | null;
            /** Training Load */
            training_load?: number | null;
            /** Vertical Oscillation Cm */
            vertical_oscillation_cm?: number | null;
            /** Vertical Ratio Percent */
            vertical_ratio_percent?: number | null;
            /** Vo2 Max */
            vo2_max?: number | null;
        };
        /** RunStreams */
        RunStreams: {
            /** Cadence Spm */
            cadence_spm?: (number | null)[] | null;
            /** Distance M */
            distance_m?: (number | null)[] | null;
            /** Elevation M */
            elevation_m?: (number | null)[] | null;
            /** Heart Rate Bpm */
            heart_rate_bpm?: (number | null)[] | null;
            /** Latitude Deg */
            latitude_deg?: (number | null)[] | null;
            /** Longitude Deg */
            longitude_deg?: (number | null)[] | null;
            /** Power W */
            power_w?: (number | null)[] | null;
            /** Speed M S */
            speed_m_s?: (number | null)[] | null;
            /** Time S */
            time_s?: number[];
            /**
             * Version
             * @default 1
             * @constant
             */
            version?: 1;
        };
        /** Setup */
        Setup: {
            athlete?: components["schemas"]["Athlete"];
            /** Days Per Week */
            days_per_week: number;
            goal: components["schemas"]["Goal"];
            /**
             * Long Run Day
             * @default 6
             */
            long_run_day?: number;
            /**
             * Race Date
             * Format: date
             */
            race_date: string;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** Status */
        Status: {
            /** Adjustments */
            adjustments: components["schemas"]["Adjustment"][];
            /** Plan Id */
            plan_id: string;
            /** Scheduled Workouts */
            scheduled_workouts: number;
            sync: components["schemas"]["SyncWindow"] | null;
            /** Weeks */
            weeks: components["schemas"]["Metrics"][];
        };
        /** Step */
        Step: {
            /** Hr Max */
            hr_max?: number | null;
            /** Hr Min */
            hr_min?: number | null;
            /** Label */
            label: string;
            /** Minutes */
            minutes: number;
            /** Pace Max */
            pace_max?: number | null;
            /** Pace Min */
            pace_min?: number | null;
        };
        /** SyncRequest */
        SyncRequest: {
            /** Activities */
            activities?: components["schemas"]["Activity"][] | null;
            /** Since */
            since?: string | null;
            /** Until */
            until?: string | null;
        };
        /** SyncResult */
        SyncResult: {
            details?: components["schemas"]["BackfillResult"] | null;
            /**
             * Since
             * Format: date
             */
            since: string;
            /** Source */
            source: string;
            /** Synced */
            synced: number;
            /**
             * Until
             * Format: date
             */
            until: string;
        };
        /** SyncWindow */
        SyncWindow: {
            /**
             * Since
             * Format: date
             */
            since: string;
            /**
             * Until
             * Format: date
             */
            until: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeekView */
        WeekView: {
            metrics: components["schemas"]["Metrics"];
            /** Workouts */
            workouts: components["schemas"]["WorkoutView"][];
        };
        /** Workout */
        Workout: {
            /**
             * Cutback
             * @default false
             */
            cutback?: boolean;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Id */
            id: string;
            kind: components["schemas"]["Kind"];
            /** Phase */
            phase: string;
            /** Steps */
            steps: components["schemas"]["Step"][];
            /** Week */
            week: number;
        };
        /** WorkoutView */
        WorkoutView: {
            /** Minutes */
            minutes: number;
            workout: components["schemas"]["Workout"];
        };
        /** WriteResult */
        WriteResult: {
            /** Action */
            action: string;
            /** Date */
            date?: string | null;
            /** Ownership Tag */
            ownership_tag?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Remote Id */
            remote_id?: string | null;
            /** Workout Id */
            workout_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_activity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_activity_streams: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStreams"] | null;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adapt_week: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdaptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Adjustment"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    propose_adjustment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_compliance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    garmin_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GarminLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarminLoginResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    garmin_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarminStatus"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    garmin_mfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GarminMFA"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarminLoginResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    garmin_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarminStatus"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setup_goal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Created"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_load: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Load"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_plan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    push_plan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    remove_owned_workouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sync_activities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_week: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
